version: '3'
services:
  mysql:
    image: "mariadb:latest"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    volumes:
      - "./sql:/docker-entrypoint-initdb.d/"
  web:
    build: ./app
    depends_on:
      - mysql
    links:
      - mysql
    ports:
     - "3001:3001"